### ISSUE TITLE
ValueError: Invalid protocol major version. Expected an integer preceded by 'v', but got uagv

### ISSUE THREAD

**Issue by a0085897** [inorbit-ai/ros_amr_interop#54]
Hello, 

I built the packages on my virtual machine and started with the vda5050_adapter_examples package, but when I run the python example as it is described, I was getting this error from the mqtt_bridge. 

<img width="923" alt="image" src="https://github.com/inorbit-ai/ros_amr_interop/assets/141137309/64400520-cf8c-4d32-8906-c5f11f7299d3">

I dived into the code to investigate and I have found the following in *utils.py* file. The strange is that the condition seems to check the *major_version*, but in reallity is checking the *interface_name* , since the *major_version* is assigned with proper value. What am I missing? because I cannot even use the vda5050_connector package. 

<img width="496" alt="image" src="https://github.com/inorbit-ai/ros_amr_interop/assets/141137309/c8035a75-5502-4d94-bfb6-6828488a7761">

Thank you in advance

**Comment by shubhamtyagii** [comment]
There is a bug in the code which I am able to identify. I'll create a pull request for the same sometime today.

**Comment by shubhamtyagii** [comment]
Here is the MR to fix your issue:[https://github.com/inorbit-ai/ros_amr_interop/pull/55]( https://github.com/inorbit-ai/ros_amr_interop/pull/55)
